### ISSUE TITLE
Please update to the latest Swift 3 syntax

### ISSUE THREAD

**Issue by DesmondPang** [0x73/SwiftIconFont#24] opened 2016-09-14 09:37 UTC
Please update to the latest Swift 3 syntax. Thank you.

**Comment by 0x73** [comment] 2016-09-14 10:02
Duplicate of #16

**Closed by 0x73** 2016-09-14 10:02 UTC

**Comment by DesmondPang** [comment] 2016-09-14 12:38
The syntax is not the latest swift 3. I am using Xcode 8 GM. Thanks
